### PR TITLE
12 hour branch

### PR DESCRIPTION
**Pull request by ericop**
Changed .css and main .js to allow for `options.twelvehour`. Since most Americans use a 12 hour AM/PM it might give the widget a broader audience. Let me know how we can make my changes better. I'm all about learning, so please point out my mistakes or places for potential improvement. Demo at http://ericop.github.io/clockpicker/

### CODE REVIEW

**Comment by ericop** [comment]
Just this morning realized there was a pull request for the 24 hour view, but it assigning a 12 hour value. I actually like that option too, I think it's more clean, however it's a very unnatural user experience  for people who don't use 24 hour clocks, so it would take some time training them to use it as it's not as intuative. Maybe we could create an option for both methods since @gitlost has a good thing going in his version too.

**Comment by weareoutman** [comment]
Thanks, it looks great

**Comment by jjharr** [comment]
Attached a concept for (IMO) a more intuitive 12-hour clock view. Don't have the time to actually do it myself though :-O

clock-am-pm-1

**Comment by ericop** [comment]
Is the idea on this one that clicking it would create a drop down? Having itnjust toggle between the two, that I could probably get behind. I think the placement of the AM/PM input up high like that probably is more intuitive, but that users on mobile devices might hit the minutes section accidentally. Good fuel for thought!

**Comment by spot-admin** [comment]
It's a one-touch toggle - basically a vertical iButton. I think the control is further away from the numbers than the numbers are from each other, so IMO it won't detract from the mobile experience.

**Pull request merged**
